version: "3"
services:
  web:
    image: giftshop
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 1000M
      restart_policy:
        condition: on-failure
    ports:
      - "11022:8080"
    networks:
      - webnet
networks:
  webnet:

